"""updates post table

Revision ID: e6a0d0b31130
Revises: e6ade040d04f
Create Date: 2025-09-18 01:18:15.294238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a0d0b31130'
down_revision = 'e6ade040d04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('is_published')
        batch_op.drop_column('excerpt')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=220), nullable=False))
        batch_op.add_column(sa.Column('excerpt', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
